nane: Dispatch on push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs‑on: ubuntu‑latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}

  dispatch-multi:
    needs: build
    strategy:
      matrix:
        repo:
          - noxhalley/contracts-go
    runs‑on: ubuntu‑latest  
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.K2_PAT }}
          repository: ${{ matrix.repo }}
          event-type: proto-schema-updated
          client-payload: |
            {
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}"
              "version": "${{ github.ref_name }}"
            }
